// Auto-generated by Next.js on first build/run. Keep the comment so the
// file isn't regenerated in a way that strips the typed-routes plugin.
// `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited. Re-run `next dev` / `next build`
// if it is missing and Next will re-create it.
